# Arquivo: .streamlit/secrets.toml

[postgres]
host = "postgresql://fisiomanager_db_e40s_user:qD6t3f2p8CMWRFFWjinESwav4pzEYTIh@dpg-d4ucqs0gjchc73c6jlp0-a/fisiomanager_db_e40s"
port = "5432"
dbname = "fisiomanager_db"
user = "fisiomanager_db_e40s_user"
password = "qD6t3f2p8CMWRFFWjinESwav4pzEYTIh"